### ISSUE TITLE
请教m3u8的问题

### ISSUE THREAD

**Issue by likeconan** [ChinaChailu/HLS-m3u8-Custom-Encryption#3]
非常感谢你的分享

有一个疑问：

resourceLoader 方法中，当是m3u8文件时候，我发现你调用了M3u8Request方法，下载文件进行了缓存，请问是必须要下载吗？

是否可以和ts一样直接redirect呢？ （试过redirect发现没办法通过）

**Comment by LastNeo** [comment]
不能直接redirect ，苹果设置了相关限制防止redirect 下载后播放，不过也有些绕过方法，就是自己搭本地服务，然后把redirect后的ts文件填充进去，理论上是可行的

**Comment by likeconan** [comment]
好的，多谢指导
